### ISSUE TITLE
Strings with a number and whitespaces are considered numeric

### ISSUE THREAD

**Issue by vladshcherbin** [danikaze/npm-vanilla-type-check#1]
Hey, should a string with whitespaces be numeric:

```js
var typeCheck = require('vanilla-type-check')
console.log(typeCheck.isNumeric('   3 ')) // -> true
```

I'd expect it to be false.

**Comment by danikaze** [comment]
I see what you mean. It's numeric because it can be translated to a number.
i.e. if the user says... I have "   3 " apples. You know it's 3 apples.
But for the "strictness" you want to check actually there's another function which is `isNumber` and should return `false`.
`isNumeric('   3 ') // true`
`isNumber('   3 ') // false`

**Comment by vladshcherbin** [comment]
@danikaze yep, you're probably right.

I was fooled by the differences of what is considered `numeric` in different languages. I checked this in php with native `is_numeric` function and the result was `false`. A bit later I came back and checked [this two versions](https://repl.it/repls/WeeInfamousAsianpiedstarling) and remembered how retarded php is 🤦‍♂️

Thanks and sorry for bothering.

**Comment by danikaze** [comment]
No problem! 
I don't remember exactly when I designed it what I was thinking, but yeah, as long as the 2 flavours are there I guess it should be ok! :D
I hope you find it useful
